import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import pages from "./data";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageSlugs = Object.keys(pages);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            {pageSlugs.map((slug) => (
              <li key={`${pages[slug].title}-link`}>
                <Link href={slug}>{pages[slug].title}</Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
