import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import pages from "./data";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageSlugs = Object.keys(pages);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          These routes are ommitted from generateStaticParams. They all have
          data in the &quot;mock CMS&quot; which is just a file in the src directory.
          Running this locally, all these routes render.
          <br />
          <ul>
            {pageSlugs.map((slug) => (
              <li key={`${pages[slug].title}-link`}>
                <Link href={slug[0] === "/" ? slug : `/${slug}`}>
                  {pages[slug].title}
                </Link>
              </li>
            ))}
          </ul>
          For good measure, here&apos;s a route that should 404:
          <ul>
            <li key={`404-link`}>
              <Link href="/this-goes-nowhere">This Goes Nowhere</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
